---
name: Formatting

'on': [pull_request_target]

jobs:
  formatting:
    name: check PR formatting
    uses: alisw/ali-bot/.github/workflows/c++-code-formatting.yml
    secrets:
      alibuild_github_token: ${{ secrets.ALIBUILD_GITHUB_TOKEN }}
